/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoExame;
import fatec.poo.control.DaoMedicacao;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.DaoPaciente;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Beatriz-Camargo
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarra = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemMarcarConsulta = new javax.swing.JMenuItem();
        jMenuItemMarcarExame = new javax.swing.JMenuItem();
        jMenuItemPrescreverMedicacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica POO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenuCadastro.setText("Cadastro");

        jMenuItemMedico.setText("Medico");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMedico);

        jMenuItemPaciente.setText("Paciente");
        jMenuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPaciente);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemSair);

        jMenuBarra.add(jMenuCadastro);

        jMenuRegistro.setText("Registro");

        jMenuItemMarcarConsulta.setText("Marcar Consulta");
        jMenuItemMarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcarConsultaActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemMarcarConsulta);

        jMenuItemMarcarExame.setText("Prescrever Medicacao");
        jMenuItemMarcarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcarExameActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemMarcarExame);

        jMenuItemPrescreverMedicacao.setText("Prescrever Medicacao");
        jMenuItemPrescreverMedicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrescreverMedicacaoActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemPrescreverMedicacao);

        jMenuBarra.add(jMenuRegistro);

        setJMenuBar(jMenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    try {
        if (conexao != null) {
            conexao.close();
            System.out.println("Conexão fechada.");
        }
    } catch (Exception ex) {
        System.out.println("Erro ao fechar conexão: " + ex.getMessage());
    }
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItemMarcarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcarExameActionPerformed
      //  GuiMarcarExame gui = new GuiMarcarExame(conexao, daoExame, daoConsulta);
      //  gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcarExameActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
      //  GuiCadastroMedico gui = new GuiCadastroMedico(conexao, daoMedico);
      //  gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteActionPerformed
       // GuiCadastroPaciente gui = new GuiCadastroPaciente(conexao, daoPaciente);
       // gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemPacienteActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcarConsultaActionPerformed
       // GuiMarcarConsulta gui = new GuiMarcarConsulta(conexao, daoConsulta, daoMedico, daoPaciente);
       // gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcarConsultaActionPerformed

    private void jMenuItemPrescreverMedicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrescreverMedicacaoActionPerformed
       // GuiPrescreverMedicacao gui = new GuiPrescreverMedicacao(conexao, daoMedicacao, daoConsulta);
       // gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrescreverMedicacaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
        conexao = DriverManager.getConnection(
            "jdbc:ucanaccess://C:\\Users\\Victorleonardo\\Documents\\NetBeansProjects\\prjPOOBeatrizIsaqueVictor\\src\\fatec\\poo\\basededados\\DBClinica.accdb"
        );

        daoMedico = new DaoMedico(conexao);
        daoPaciente = new DaoPaciente(conexao);
        daoConsulta = new DaoConsulta(conexao);
        daoMedicacao = new DaoMedicacao(conexao);
        daoExame = new DaoExame(conexao);

        System.out.println("Conexão estabelecida.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao conectar: " + ex.getMessage());
    }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemMarcarConsulta;
    private javax.swing.JMenuItem jMenuItemMarcarExame;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemPrescreverMedicacao;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRegistro;
    // End of variables declaration//GEN-END:variables
    private Connection conexao;
    private DaoMedico daoMedico;
    private DaoPaciente daoPaciente;
    private DaoConsulta daoConsulta;
    private DaoMedicacao daoMedicacao;
    private DaoExame daoExame;

}
