/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoExame;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Exame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author Beatriz-Camargo
 */
public class GuiMarcarExame extends javax.swing.JFrame {

    /**
     * Creates new form GuiMarcarExame
     */
    public GuiMarcarExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtCodigoConsulta = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        btnConsultarConsulta = new javax.swing.JButton();
        lblNomeMedico = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        txtHorario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marcar Exame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Código Consulta");

        txtCodigoConsulta.setEnabled(false);

        jLabel3.setText("Descrição");

        txtDescricao.setEnabled(false);

        jLabel4.setText("Data");

        jLabel5.setText("Horário");

        jLabel6.setText("Valor");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);

        btnConsultarConsulta.setText("...");
        btnConsultarConsulta.setEnabled(false);
        btnConsultarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConsultaActionPerformed(evt);
            }
        });

        lblNomeMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeMedico.setEnabled(false);

        jLabel8.setText("Médico");

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtValor.setEnabled(false);

        txtHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtHorario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnConsultar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnInserir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSair))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtCodigoConsulta))
                            .addGap(18, 18, 18)
                            .addComponent(btnConsultarConsulta)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(lblNomeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtDescricao)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtHorario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeMedico)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultarConsulta)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblNomeMedico, txtCodigo, txtCodigoConsulta, txtData});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preparaConexao = new PreparaConexao("", ""); //Usuário e senha                            
        preparaConexao.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        preparaConexao.setConnectionString("jdbc:ucanaccess://C:\\Users\\Beatriz Camargo\\Documents\\NetBeansProjects\\poo-sistema-clinica\\src\\fatec\\poo\\basededados\\DBClinica.accdb");

        Connection conexao = preparaConexao.abrirConexao();

        daoExame = new DaoExame(conexao);
        daoConsulta = new DaoConsulta(conexao);
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        exame = null;

        int codigo = 0;

        try {
            codigo = Integer.parseInt(txtCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao consultar um exame. Verifique os dados inseridos.");

            txtCodigo.requestFocus();
            return;
        }

        exame = daoExame.consultar(codigo);

        btnConsultar.setEnabled(false);
        if (exame == null) {
            btnInserir.setEnabled(true);
            btnConsultarConsulta.setEnabled(true);

            txtCodigo.setEnabled(false);
            txtCodigoConsulta.setEnabled(true);
            txtDescricao.setEnabled(true);
            txtData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);

            txtCodigoConsulta.requestFocus();
        } else {
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);

            txtCodigo.setEnabled(false);
            txtCodigoConsulta.setEnabled(false);
            txtDescricao.setEnabled(true);
            txtData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);

            txtCodigo.setText(String.valueOf(exame.getCodigo()));
            txtCodigoConsulta.setText(String.valueOf(exame.getConsulta().getCodigo()));
            txtDescricao.setText(exame.getDescricao());
            txtData.setText(exame.getData());
            txtHorario.setText(exame.getHorario());
            txtValor.setText(String.valueOf(exame.getValor()));
            lblNomeMedico.setText(exame.getConsulta().getMedico().getNome());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConsultaActionPerformed
        lblNomeMedico.setText(null);

        consulta = null;

        int codigoConsulta = 0;

        try {
            codigoConsulta = Integer.parseInt(txtCodigoConsulta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao consultar consulta. Verifique os dados inseridos.", "Erro de formatação", JOptionPane.ERROR_MESSAGE);

            txtCodigoConsulta.requestFocus();
            return;
        }

        consulta = daoConsulta.consultar(codigoConsulta);

        if (consulta == null) {
            JOptionPane.showMessageDialog(null, "Consulta não cadastrada");

            txtCodigoConsulta.requestFocus();
        } else {
            lblNomeMedico.setText(consulta.getMedico().getNome());

            lblNomeMedico.setEnabled(false);
            txtCodigoConsulta.setEnabled(false);
            btnConsultarConsulta.setEnabled(false);

            txtDescricao.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarConsultaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        preparaConexao.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        exame = null;
        consulta = null;

        exame = new Exame(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText());

        if (!isValidoTodosOsCamposObrigatorios()) {
            return;
        }

        int codigoConsulta = 0;

        try {
            codigoConsulta = Integer.parseInt(txtCodigoConsulta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O campo código consulta só aceita números. Verifique os dados inseridos.");

            txtCodigo.requestFocus();
            return;
        }

        consulta = daoConsulta.consultar(codigoConsulta);

        if (consulta != null) {
            consulta.addExame(exame);
            exame.setData(txtData.getText());
            exame.setValor(formatarValor());
            exame.setHorario(txtHorario.getText());

            daoExame.inserir(exame);

            resetarFormulario();
        } else {
            JOptionPane.showMessageDialog(null, "Consulta não cadastrada");

            txtCodigoConsulta.requestFocus();
        }

        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            consulta.removeExame(exame);
            daoExame.excluir(exame);
        }

        resetarFormulario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (!isValidoTodosOsCamposObrigatorios()) {
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
            exame.setDescricao(txtDescricao.getText());
            exame.setData(txtData.getText());
            exame.setHorario(txtHorario.getText());
            exame.setValor(formatarValor());
            
            consulta.addExame(exame);

            daoExame.alterar(exame);

            resetarFormulario();
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void resetarFormulario() {
        txtCodigo.setText(null);
        txtCodigoConsulta.setText(null);
        lblNomeMedico.setText(null);
        txtDescricao.setText(null);
        txtValor.setText(null);
        txtHorario.setText(null);
        txtData.setText(null);

        txtCodigo.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtData.setEnabled(false);
        txtValor.setEnabled(false);
        txtHorario.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }

    private boolean isCampoObrigatorioValido(JTextField campo, String nomeCampo) {
        
        String textoDoCampo = campo.getText();

        String textoSemMascara;

        if (nomeCampo.contains("Data")) {
            textoSemMascara = textoDoCampo.replace("/", "");
        } else {
            textoSemMascara = textoDoCampo;
        }
        
        textoSemMascara = textoSemMascara.trim();

        if (textoSemMascara.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "O campo " + nomeCampo + " é obrigatório! Por favor, preencha-o.",
                    "Campo obrigatório",
                    JOptionPane.ERROR_MESSAGE
            );

            campo.requestFocus();

            return false;
        }
        return true;
    }

    private boolean isValidoTodosOsCamposObrigatorios() {
        return (isCampoObrigatorioValido(txtCodigoConsulta, "Código Consulta")
                && isCampoObrigatorioValido(txtDescricao, "Descrição")
                && isCampoObrigatorioValido(txtData, "Data")
                && isCampoObrigatorioValido(txtHorario, "Horário"));
    }

    private double formatarValor() {
        String textoValor = txtValor.getText();
        
        NumberFormat formatador = NumberFormat.getInstance(new Locale("pt", "BR"));

        Number numero;
        try {
            numero = formatador.parse(textoValor);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "O campo valor só aceita números. Verifique os dados inseridos.");
            return 0.00;
        }

        return numero.doubleValue();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtHorario;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private PreparaConexao preparaConexao;
    private DaoExame daoExame;
    private DaoConsulta daoConsulta;
    private Consulta consulta;
    private Exame exame;
}
