/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoMedicacao;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Medicacao;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author isaqu
 */
public class GuiPrescreverMedicacao extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrescreverMedicacao_Nova
     */
    public GuiPrescreverMedicacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigoConsulta = new javax.swing.JTextField();
        txtDosagem = new javax.swing.JTextField();
        txtQuantidadeDias = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnConsultarCodigoConsulta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblNomeMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescrever Medicação");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Código Consulta");

        jLabel3.setText("Dosagem");

        jLabel4.setText("Quantidade Dias");

        txtCodigoConsulta.setEnabled(false);

        txtDosagem.setEnabled(false);

        txtQuantidadeDias.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consutlar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultarCodigoConsulta.setText("...");
        btnConsultarCodigoConsulta.setEnabled(false);
        btnConsultarCodigoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoConsultaActionPerformed(evt);
            }
        });

        jLabel5.setText("Medico");

        lblNomeMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtQuantidadeDias, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(txtDosagem)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCodigoConsulta, txtDosagem, txtNome, txtQuantidadeDias});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel5))
                        .addComponent(btnConsultarCodigoConsulta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtQuantidadeDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSair)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnInserir)
                    .addComponent(btnConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nomeMedicacao = this.txtNome.getText();
        if(nomeMedicacao.isEmpty()){
            this.exibirMensagemErro("O campo 'nome' não pode ficar vazio.");
            return;
        }
        
        medicacao = this.daoMedicacao.consultar(nomeMedicacao);
        if(medicacao == null){
            this.habilitarCampoConsulta();
        }else {
            Integer codigoConsulta = daoMedicacao.consultarConsultaPorNome(nomeMedicacao);
            consulta = daoConsulta.consultar(codigoConsulta);
            this.txtCodigoConsulta.setText(String.valueOf(consulta.getCodigo()));
            this.lblNomeMedico.setText(consulta.getMedico().getNome());
            this.preencherFormulario();
            this.habilitarAtualizar();
        }
        
        
        this.txtNome.setEnabled(false);
        this.txtDosagem.requestFocus();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(!this.isValidoTodosOsCamposObrigatorios()){
            return;
        }
        
        this.medicacao = new Medicacao(this.txtNome.getText());
        
        this.pegarValoresFormulario();
        
        this.daoMedicacao.inserir(medicacao, consulta.getCodigo());
        
        this.resetarFormulario();
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(!this.isValidoTodosOsCamposObrigatorios()){
            return;
        }
        if(JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            this.pegarValoresFormulario();
            this.daoMedicacao.alterar(medicacao);
            this.resetarFormulario();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "Exclusão", JOptionPane.YES_NO_OPTION) == 0){
            this.daoMedicacao.excluir(medicacao.getNome());
            this.resetarFormulario();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.prepConn = new PreparaConexao("", "");
        this.prepConn.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        this.prepConn.setConnectionString("jdbc:ucanaccess://C:\\Users\\isaqu\\Desktop\\codes\\ProgBanco\\NeteBeansProjects\\prjPOOBeatrizIsaqueVictor\\prjPOO\\src\\fatec\\poo\\basededados\\DBClinica.accdb");

        Connection conn = this.prepConn.abrirConexao();
        this.daoMedicacao = new DaoMedicacao(conn);
        this.daoConsulta = new DaoConsulta(conn);
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarCodigoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoConsultaActionPerformed
        String codigoConsulta = this.txtCodigoConsulta.getText();
        try {
            Integer.parseInt(codigoConsulta);
        } catch (NumberFormatException nfe) {
            this.exibirMensagemErro("O campo 'Código Consulta' deve ser um número.");
            return;
        }
        
        
        if(codigoConsulta.isEmpty()){
            this.exibirMensagemErro("O campo 'Código Consulta' não pode ficar vazio.");
            return;
        }
        
        consulta = this.daoConsulta.consultar(Integer.parseInt(codigoConsulta));
        
        if(consulta == null){
            this.exibirMensagemErro("Consulta não encontrada");
            return;
        }
        
        
        this.lblNomeMedico.setText(consulta.getMedico().getNome());;
        this.habilitarCriar();
    }//GEN-LAST:event_btnConsultarCodigoConsultaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.prepConn.fecharConexao();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCodigoConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JTextField txtDosagem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidadeDias;
    // End of variables declaration//GEN-END:variables
    private PreparaConexao prepConn;
    private DaoMedicacao daoMedicacao;
    private Medicacao medicacao;
    private DaoConsulta daoConsulta;
    private Consulta consulta;
    
    private void exibirMensagemErro(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private boolean isCampoObrigatorioValido(JTextField campo, String nomeCampo) {

        String textoDoCampo = campo.getText().trim();

        if (textoDoCampo.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "O campo " + nomeCampo + " é obrigatório! Por favor, preencha-o.",
                    "Campo obrigatório",
                    JOptionPane.ERROR_MESSAGE
            );

            campo.requestFocus();

            return false;
        }
        return true;
    }

    private boolean isValidoTodosOsCamposObrigatorios() {
        return (isCampoObrigatorioValido(txtNome, "Nome")
                && isCampoObrigatorioValido(txtCodigoConsulta, "Código Consulta")
                && isCampoObrigatorioValido(txtDosagem, "Dosagem")
                && isCampoObrigatorioValido(txtQuantidadeDias, "Quantidade Dias"));
    }
    
    private void habilitarCampoConsulta(){
        this.txtCodigoConsulta.setEnabled(true);
        this.btnConsultarCodigoConsulta.setEnabled(true);
    }
    
    private void habilitarCriar(){
        this.txtCodigoConsulta.setEnabled(false);
        this.btnConsultarCodigoConsulta.setEnabled(false);
        this.btnConsultar.setEnabled(false);
        
        
        this.txtDosagem.setEnabled(true);
        this.txtQuantidadeDias.setEnabled(true);   
    
        this.btnInserir.setEnabled(true);
    }
    
    private void habilitarAtualizar(){
        this.txtCodigoConsulta.setEnabled(false);
        this.btnConsultarCodigoConsulta.setEnabled(false);
        this.btnConsultar.setEnabled(false);
        
        
        this.txtDosagem.setEnabled(true);
        this.txtQuantidadeDias.setEnabled(true);   
    
        this.btnAlterar.setEnabled(true);
        this.btnExcluir.setEnabled(true);
    }
    
    private void pegarValoresFormulario(){
        this.medicacao.setDosagem(this.txtDosagem.getText());
        this.medicacao.setQtdeDias(Integer.parseInt(this.txtQuantidadeDias.getText()));
    }
    
    private void preencherFormulario(){
        this.txtNome.setText(this.medicacao.getNome());
        this.txtDosagem.setText(this.medicacao.getDosagem());
        this.txtQuantidadeDias.setText(String.valueOf(this.medicacao.getQtdeDias()));
    }
    
    private void resetarFormulario(){
        this.txtNome.setText("");
        this.txtCodigoConsulta.setText("");
        this.txtDosagem.setText("");
        this.txtQuantidadeDias.setText("");
        this.lblNomeMedico.setText("");
        
        this.txtNome.setEnabled(true);
        this.txtCodigoConsulta.setEnabled(false);
        this.txtDosagem.setEnabled(false);
        this.txtQuantidadeDias.setEnabled(false);
        
        this.btnAlterar.setEnabled(false);
        this.btnConsultar.setEnabled(true);
        this.btnConsultarCodigoConsulta.setEnabled(false);
        this.btnExcluir.setEnabled(false);
        this.btnInserir.setEnabled(false);
    }
}
